
export const Graph_info = [
    {
        id:0,
        crimeType:'Arson',
        crimeRate:0,
        date:'',
    },
    {
        id:1,
        crimeType:'Burglary',
        crimeRate:0,
        date:'',
    },
    {
        id:2,
        crimeType:'Carjacking',
        crimeRate:0,
        date:'',
    },
    {
        id:3,
        crimeType:'Homicide',
        crimeRate:0,
        date:'',
    },
    {
        id:4,
        crimeType:'Human trafficking',
        crimeRate:0,
        date:'',
    },
    {
        id:5,
        crimeType:'Illegal drug trade',
        crimeRate:0,
        date:'',
    },
    {
        id:6,
        crimeType:'Kidnapping',
        crimeRate:0,
        date:'',
    },
    {
        id:7,
        crimeType:'Murder',
        crimeRate:0,
        date:'',
    },
    {
        id:8,
        crimeType:'Theft',
        crimeRate:0,
        date:'',
    },
    {
        id:9,
        crimeType:'Vandlism',
        crimeRate:0,
        date:'',
    },
    {
        id:10,
        crimeType:'Violence',
        crimeRate:0,
        date:'',
    },
]